# Generated by Django 3.0.8 on 2020-07-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_auto_20200727_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfb',
            name='modal',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
